### PR TITLE
1.19.4 Support — Version 4.5.16

### PR DESCRIPTION
**Pull request by JustOneMoreBlock**

### CODE REVIEW

**Comment by Leahcimkrob** [comment]
Sorry, but I get this massage:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.813 s
[INFO] Finished at: 2023-03-21T14:20:55+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project nametagedit: Could not resolve dependencies for project com.nametagedit:nametagedit:jar:4.5.16: Failed to collect dependencies at co.aikar:acf-paper:jar:0.5.1-SNAPSHOT: Failed to read artifact descriptor for co.aikar:acf-paper:jar:0.5.1-SNAPSHOT: The following artifacts could not be resolved: co.aikar:acf-parent:pom:0.5.1-SNAPSHOT (present, but unavailable): Could not find artifact co.aikar:acf-parent:pom:0.5.1-20221114.001801-23 in guilds (https://repo.glaremasters.me/repository/public/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by Log1x** [comment]
Not sure why Aikar was added in the first place. I tried removing it and it looks like it's trying to forcefully pull it in from a dependency but I'm not sure which. Aikar isn't actually being used in NametagEdit and shading it in would add multiple mb to the jar size for no reason.

**Edit**: Looks like its the dependency on the Guilds plugin for its hook is causing this issue.

**Comment by Leahcimkrob** [comment]
Is there already an NTE that works with MC 1.19.4? The dev is taking a long time again.

**Comment by BySwiizen** [comment]
Please update!

**Pull request merged**
