### PR TITLE
1.17 update + some cleanup

### PR DESCRIPTION
**Pull request by Aurelien30000**
Hey,

This pr has been tested under different circumstances and works perfectly on 1.16.5- and 1.17+!
Cleanup is mainly aimed at improving code format and fixing typos.

If you would consider another implementation or approach to deal with new mojang mappings, dion't hesitate.
These changes indeed force us to review all packets/nms management, specifically for 1.17+.

_Small question: are you interested in using github actions to verify commits and provide allartifacts? I might setup them easily._

### CODE REVIEW

**Comment by JustOneMoreBlock** [comment]
Does this add hex color support?

**Comment by Aurelien30000** [comment]
I haven't changed anything about that, I have just taken the changes from the branch dev.

**Comment by JustOneMoreBlock** [comment]
```
4.06 00:16:06 [Server] ERROR java.lang.NullPointerException
14.06 00:16:06 [Server] WARN java.lang.NullPointerException
14.06 00:16:06 [Server] WARN at net.minecraft.server.v1_16_R3.PacketDataSerializer.a(PacketDataSerializer.java:192)
14.06 00:16:06 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayOutScoreboardTeam.b(PacketPlayOutScoreboardTeam.java:116)
14.06 00:16:06 [Server] WARN at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:46)
14.06 00:16:06 [Server] WARN at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:15)
14.06 00:16:06 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
14.06 00:16:06 [Server] WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
14.06 00:16:06 [Server] WARN at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:323)
14.06 00:16:06 [Server] WARN at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
14.06 00:16:06 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
14.06 00:16:06 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
14.06 00:16:06 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
14.06 00:16:06 [Server] WARN at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
14.06 00:16:06 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:829)
```
NPE

**Comment by Aurelien30000** [comment]
Did you notice any revelant about how to reproduce this error? Also, it's not as easy, as long as it depends exclusively on your minecraft server code, I don't see which field could be null tbh.

**Pull request merged**
