### PR TITLE
4.5.5

### PR DESCRIPTION
**Pull request by Aurelien30000**
- 1.18.2 support
- Bump luckperms-api version

### CODE REVIEW

**Comment by Aurelien30000** [comment]
[NametagEdit.zip](https://github.com/sgtcaze/NametagEdit/files/8204513/NametagEdit.zip)

**Comment by cicatrice74** [comment]
thanks a lot for the update

**Comment by JohnsanGeezo** [comment]
So this is the version to use on 1.18.2?

**Comment by Aurelien30000** [comment]
@JohnsanGeezo Yes, you can also download the latest dev (1.18.2) version here: https://ci.nametagedit.com/job/NametagEdit-Dev/changes

**Pull request merged**
