### PR TITLE
Fix and improve a few things.

### PR DESCRIPTION
**Pull request by Aurelien30000**
~~Currently waiting to fix the issue below:~~

> ```
> 4.06 00:16:06 [Server] ERROR java.lang.NullPointerException
> 14.06 00:16:06 [Server] WARN java.lang.NullPointerException
> 14.06 00:16:06 [Server] WARN at net.minecraft.server.v1_16_R3.PacketDataSerializer.a(PacketDataSerializer.java:192)
> 14.06 00:16:06 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayOutScoreboardTeam.b(PacketPlayOutScoreboardTeam.java:116)
> 14.06 00:16:06 [Server] WARN at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:46)
> 14.06 00:16:06 [Server] WARN at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:15)
> 14.06 00:16:06 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
> 14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
> 14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
> 14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
> 14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
> 14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
> 14.06 00:16:06 [Server] WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
> 14.06 00:16:06 [Server] WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
> 14.06 00:16:06 [Server] WARN at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:323)
> 14.06 00:16:06 [Server] WARN at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
> 14.06 00:16:06 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
> 14.06 00:16:06 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
> 14.06 00:16:06 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 14.06 00:16:06 [Server] WARN at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 14.06 00:16:06 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:829)
> ```
> 
> NPE

### CODE REVIEW

**Comment by JustOneMoreBlock** [comment]
@Aurelien30000 Has this been completed?

**Comment by Aurelien30000** [comment]
> @Aurelien30000 Has this been completed?

Almost, I just need steps to reproduce the issue you reported _(pasted above)_, and then _fix_ it.

**Comment by JustOneMoreBlock** [comment]
The only thing I did was:

```
/nte player NametagEdit prefix '&#HEXCODEHi &r'
```
But, it doesn't do it now. I think there was a change in the recent builds. The old `Hex Code Support` still exists, however, isn't functional.

A colleague of mine has a few devs poking it and seeing if they can add the Hex Color support.

But, the way dev2 branch is looking. Everything seems to be completely working like it should

**Comment by Aurelien30000** [comment]
Okay, so these patches are ready!

**Pull request merged**
