### PR TITLE
1.20.2 Support fix

### PR DESCRIPTION
**Pull request by Aurelien30000**
Fixes https://github.com/sgtcaze/NametagEdit/issues/881

- Some improvements
- Fix 1.20.2 support (mangled priority fetching PlayerConnection#sendPacket method)

### CODE REVIEW

**Comment by Aurelien30000** [comment]
[NametagEdit.zip](https://github.com/sgtcaze/NametagEdit/files/12910365/NametagEdit.zip)

**Comment by jonawoning** [comment]
Add support for the playername to be hex

**Comment by DieserEliasYT** [comment]
i get this error everytime.. [mclo.gs](https://mclo.gs/qFPQWmq)

**Comment by Aurelien30000** [comment]
> i get this error everytime.. [mclo.gs](https://mclo.gs/qFPQWmq)

You should:
- Update Paper
- Use the NameTagEdit I provided above, the version has not been officially released yet ;)

**Comment by timmyb4** [comment]
this works great for me.

**Comment by BeaSHyneGG** [comment]
Hello. The plugin does not work on 1.20.4. There is a solution?

**Comment by Aurelien30000** [comment]
> Hello. The plugin does not work on 1.20.4. There is a solution?

Thanks for the feedback, I will take a look.

**Comment by JustOneMoreBlock** [comment]
This works, try the latest builds. It's on Spigot too.

**Comment by GWServer** [comment]
Fix the prefix issue. Test Paper 1.18.2 (bungeecord) I set the &c& prefix for one player and he crashes from the server on version 1.8 - 1.12.2 
Error in his client:
[00:41:33] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
at avo.a(SourceFile:276) ~[1.8.8.jar:?]
at bfk.a(SourceFile:1021) ~[1.8.8.jar:?]
at ave.av(SourceFile:915) ~[1.8.8.jar:?]
at ave.a(SourceFile:325) [1.8.8.jar:?]
at net.minecraft.client.main.Main.main(SourceFile:124) [1.8.8.jar:?]

**Comment by Aurelien30000** [comment]
> Fix the prefix issue. Test Paper 1.18.2 (bungeecord) I set the &c& prefix for one player and he crashes from the server on version 1.8 - 1.12.2 Error in his client: [00:41:33] [Client thread/FATAL]: Unreported exception thrown! java.lang.NullPointerException at avo.a(SourceFile:276) ~[1.8.8.jar:?] at bfk.a(SourceFile:1021) ~[1.8.8.jar:?] at ave.av(SourceFile:915) ~[1.8.8.jar:?] at ave.a(SourceFile:325) [1.8.8.jar:?] at net.minecraft.client.main.Main.main(SourceFile:124) [1.8.8.jar:?]

That's not likely a NameTagEdit issue. Please create an appropriate issue with relevant information and test wisely your setup.

**Comment by sergservis** [comment]
I tested it. I created a clean build with minimal plugins. This is either a problem with bungeecord or with NameTagEdit
If I run without bungeecord, then this problem does not exist.

**Comment by GWServer** [comment]
I created. Take this problem seriously. My server is 5 years old and I can say that I have a lot of experience in testing these problems.
https://github.com/sgtcaze/NametagEdit/issues/898

**Comment by GWServer** [comment]
Fix 1.20.4 support 
[23:59:31 INFO]: [NametagEdit] Disabling NametagEdit v4.5.21
[23:59:31 ERROR]: Error occurred while disabling NametagEdit v4.5.21
java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.NametagManager.reset()" because "this.manager" is null
        at com.nametagedit.plugin.NametagEdit.onDisable(NametagEdit.java:86) ~[NametagEdit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[paper-1.20.4.jar:git-Paper-451]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-451]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.20.4.jar:git-Paper-451]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-451]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-451]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-451]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-451]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-451]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-451]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-451]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-451]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Pull request merged**
